baseurl = "http://caveconfessions.com/"
languageCode = "en-us"
title = "Cave Confessions"
paginate = 5
Copyright = "All rights reserved - 2015"

[params]
    description = "Out of the mouths of caves"
    cover = "images/cover.jpg"
    author = "Joshua Barone"
    logo = "images/profile.png"

[permalinks]
    post = "/:slug/"
